### PR TITLE
Removed a substitution for a guide that no longer exists.

### PR DESCRIPTION
**Pull request by shefulloflight**
The _Amazon SQS Getting Started Guide_ has been retired. The most current information is in the _Amazon SQS Developer Guide_: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-tutorials.html

### CODE REVIEW

**Comment by shefulloflight** [comment]
@hyandell @joshbean @EronHennessey @pccornel @huntsper Hi, could someone please merge in these changes? :smile:

**Comment by EronHennessey** [comment]
Hi @mig281, Do we know if any guides are still using this?  We should scrub docs for this.  Otherwise, it should probably (temporarily) resolve to the SQS Developer Guide...

**Comment by EronHennessey** [comment]
I just checked through the source in all of the [awsdocs](https://github.com/awsdocs) repos, and couldn't find any instances. I think it's fine. It'll definitely reduce the possibility of someone adding a reference to a missing guide later.  Thanks @mig281!

**Comment by shefulloflight** [comment]
@EronHennessey A few months ago, Ann B. helped me drive the effort to get rid of the GSG in other docs sets. We _should_ be OK. In addition, the old docs links redirects to the new docs in the dev guide correctly. I wouldn't make any substitutions beyond this for now.

**Pull request merged**
